spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Spanis@MySQL57

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
        type: trace